from app.schemas.parcel import ParcelStatus
from app.schemas.tracking import TrackingEvent


def seed_additional_tracking() -> dict[str, list[TrackingEvent]]:
    return {
        "AWEN-2026-0008": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-20", time="09:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-20", time="11:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-21", time="08:00", location="Autopista Valencia-Maturin", lat=9.8000, lng=-65.5000, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-23", time="14:30", location="Sucursal Sur", lat=9.7480, lng=-63.1789, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-25", time="09:00", location="Sucursal Sur", lat=9.7480, lng=-63.1789, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0009": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-25", time="10:30", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0010": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-22", time="08:00", location="Sucursal Occidental", lat=10.0678, lng=-69.3467, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-22", time="10:00", location="Sucursal Occidental", lat=10.0678, lng=-69.3467, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-23", time="07:30", location="Autopista Merida-Barquisimeto", lat=9.2000, lng=-70.0000, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-25", time="11:00", location="Sucursal Sur", lat=10.0678, lng=-69.3467, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-28", time="09:30", location="Sucursal Sur", lat=10.0678, lng=-69.3467, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0011": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-18", time="09:00", location="Sucursal Costa", lat=10.2469, lng=-67.5958, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-18", time="11:30", location="Sucursal Costa", lat=10.2469, lng=-67.5958, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-19", time="08:00", location="Autopista Maracay-Merida", lat=9.5000, lng=-69.0000, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-21", time="15:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-22", time="09:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date="2026-05-23", time="11:30", location="Av. Bolivar 456, Merida", lat=8.5983, lng=-71.1476, operator="Conductor Ana", completed=True),
        ],
        "AWEN-2026-0012": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-24", time="08:30", location="Sucursal Sur", lat=9.7480, lng=-63.1789, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-24", time="10:00", location="Sucursal Sur", lat=9.7480, lng=-63.1789, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-25", time="06:00", location="Autopista Maturin-Maracaibo", lat=10.0000, lng=-67.0000, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-27", time="13:00", location="Sucursal Norte", lat=10.6545, lng=-71.6506, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-29", time="09:00", location="Sucursal Norte", lat=10.6545, lng=-71.6506, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0013": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-28", time="14:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0014": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-26", time="09:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-27", time="10:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0015": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-23", time="10:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-23", time="12:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-24", time="08:00", location="Autopista Merida-San Cristobal", lat=8.0000, lng=-71.5000, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-26", time="10:30", location="Sucursal Central", lat=7.7682, lng=-72.2284, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-28", time="09:00", location="Sucursal Central", lat=7.7682, lng=-72.2284, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0016": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-21", time="08:00", location="Sucursal Sur", lat=10.0678, lng=-69.3467, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-21", time="10:00", location="Sucursal Sur", lat=10.0678, lng=-69.3467, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-22", time="06:30", location="Autopista Barquisimeto-Caracas", lat=10.2000, lng=-68.0000, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-24", time="12:00", location="Sucursal Central", lat=10.4806, lng=-66.9036, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-26", time="09:00", location="Sucursal Central", lat=10.4806, lng=-66.9036, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0017": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-20", time="09:00", location="Sucursal Sur", lat=8.3519, lng=-62.6414, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-20", time="11:00", location="Sucursal Sur", lat=8.3519, lng=-62.6414, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-21", time="08:00", location="Autopista Ciudad Guayana-Barquisimeto", lat=9.5000, lng=-65.0000, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-23", time="14:00", location="Sucursal Sur", lat=10.0678, lng=-69.3467, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-27", time="09:30", location="Sucursal Sur", lat=10.0678, lng=-69.3467, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date="2026-05-29", time="10:00", location="Av. Bolivar 890, Barquisimeto", lat=10.0678, lng=-69.3467, operator="Conductor Pedro", completed=True),
        ],
        "AWEN-2026-0018": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-25", time="08:00", location="Sucursal Norte", lat=10.6545, lng=-71.6506, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-25", time="10:00", location="Sucursal Norte", lat=10.6545, lng=-71.6506, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-26", time="07:00", location="Autopista Maracaibo-Maracay", lat=10.2000, lng=-69.0000, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-28", time="11:00", location="Sucursal Costa", lat=10.2469, lng=-67.5958, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-30", time="09:00", location="Sucursal Costa", lat=10.2469, lng=-67.5958, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0019": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-30", time="10:00", location="Sucursal Norte", lat=10.6545, lng=-71.6506, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0020": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-27", time="09:30", location="Sucursal Costa", lat=10.2469, lng=-67.5958, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-28", time="10:00", location="Sucursal Costa", lat=10.2469, lng=-67.5958, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0021": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-22", time="08:00", location="Sucursal Este", lat=10.2067, lng=-64.6333, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-22", time="10:00", location="Sucursal Este", lat=10.2067, lng=-64.6333, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-23", time="07:00", location="Autopista Puerto La Cruz-Maracay", lat=10.2000, lng=-66.0000, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-25", time="13:00", location="Sucursal Costa", lat=10.2469, lng=-67.5958, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-27", time="09:00", location="Sucursal Costa", lat=10.2469, lng=-67.5958, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0022": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-15", time="09:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-15", time="11:30", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-16", time="08:00", location="Valencia, Carabobo", lat=10.1620, lng=-68.0077, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-17", time="10:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-18", time="09:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date="2026-05-19", time="14:00", location="Av. Andres Bello 456, Valencia", lat=10.1620, lng=-68.0077, operator="Conductor Pedro", completed=True),
        ],
        "AWEN-2026-0023": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-24", time="08:00", location="Sucursal Este", lat=8.8833, lng=-64.2500, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-24", time="10:00", location="Sucursal Este", lat=8.8833, lng=-64.2500, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-25", time="07:30", location="Autopista El Tigre-Valencia", lat=9.5000, lng=-66.0000, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-27", time="15:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-30", time="09:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0024": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-23", time="08:00", location="Sucursal Este", lat=10.1333, lng=-64.6833, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-23", time="10:30", location="Sucursal Este", lat=10.1333, lng=-64.6833, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-24", time="06:00", location="Autopista Barcelona-Merida", lat=9.0000, lng=-69.0000, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-26", time="16:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-28", time="09:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date="2026-05-29", time="11:00", location="Av. Bolivar 456, Merida", lat=8.5983, lng=-71.1476, operator="Conductor Pedro", completed=True),
        ],
        "AWEN-2026-0025": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-29", time="10:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0026": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-26", time="09:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-26", time="11:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-27", time="08:00", location="Autopista Merida-Barquisimeto", lat=9.2000, lng=-70.0000, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-29", time="10:00", location="Sucursal Sur", lat=10.0678, lng=-69.3467, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-30", time="09:00", location="Sucursal Sur", lat=10.0678, lng=-69.3467, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0027": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-21", time="08:00", location="Sucursal Sur", lat=9.7480, lng=-63.1789, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-21", time="10:00", location="Sucursal Sur", lat=9.7480, lng=-63.1789, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-22", time="07:00", location="Autopista Maturin-Merida", lat=9.5000, lng=-67.0000, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-24", time="14:30", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-27", time="09:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0028": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-25", time="08:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-25", time="10:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-26", time="07:30", location="Autopista Caracas-Ciudad Guayana", lat=9.8000, lng=-64.5000, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-28", time="12:00", location="Sucursal Sur", lat=8.3519, lng=-62.6414, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-30", time="09:00", location="Sucursal Sur", lat=8.3519, lng=-62.6414, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0029": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-24", time="08:00", location="Sucursal Norte", lat=10.6545, lng=-71.6506, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-26", time="10:00", location="Sucursal Norte", lat=10.6545, lng=-71.6506, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0030": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-30", time="09:00", location="Sucursal Sur", lat=8.3519, lng=-62.6414, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0031": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-28", time="08:00", location="Sucursal Este", lat=10.1333, lng=-64.6833, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-28", time="10:00", location="Sucursal Este", lat=10.1333, lng=-64.6833, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-29", time="07:00", location="Autopista Barcelona-Ciudad Guayana", lat=9.5000, lng=-63.5000, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-30", time="11:00", location="Sucursal Sur", lat=8.3519, lng=-62.6414, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0032": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-26", time="08:30", location="Sucursal Norte", lat=10.6545, lng=-71.6506, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-26", time="10:30", location="Sucursal Norte", lat=10.6545, lng=-71.6506, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-27", time="07:00", location="Autopista Maracaibo-Merida", lat=9.5000, lng=-71.0000, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-29", time="14:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-30", time="09:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0033": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-19", time="09:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-19", time="11:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-20", time="08:00", location="Autopista Caracas-Valencia", lat=10.3000, lng=-67.5000, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-21", time="10:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-22", time="09:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date="2026-05-24", time="11:00", location="Urb. El Bosque 789, Valencia", lat=10.1620, lng=-68.0077, operator="Conductor Ana", completed=True),
        ],
        "AWEN-2026-0034": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-27", time="08:00", location="Sucursal Este", lat=10.2067, lng=-64.6333, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-27", time="10:00", location="Sucursal Este", lat=10.2067, lng=-64.6333, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-28", time="06:00", location="Autopista Puerto La Cruz-Merida", lat=9.3000, lng=-68.0000, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-30", time="12:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0035": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-30", time="10:00", location="Sucursal Central", lat=10.4959, lng=-66.8534, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0036": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-25", time="08:00", location="Sucursal Este", lat=8.8833, lng=-64.2500, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-25", time="10:00", location="Sucursal Este", lat=8.8833, lng=-64.2500, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-26", time="07:00", location="Autopista El Tigre-Maturin", lat=9.2000, lng=-63.5000, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-28", time="14:00", location="Sucursal Sur", lat=9.7480, lng=-63.1789, operator="Operador Carlos", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-30", time="09:00", location="Sucursal Sur", lat=9.7480, lng=-63.1789, operator="Conductor Ana", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date=None, time=None, location=None, lat=None, lng=None, operator=None, completed=False),
        ],
        "AWEN-2026-0037": [
            TrackingEvent(step=ParcelStatus.REGISTERED, date="2026-05-10", time="10:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.PICKED_UP, date="2026-05-10", time="12:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.IN_TRANSIT, date="2026-05-11", time="08:00", location="Merida, Merida", lat=8.5983, lng=-71.1476, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.AT_DESTINATION_BRANCH, date="2026-05-12", time="10:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Operador Maria", completed=True),
            TrackingEvent(step=ParcelStatus.OUT_FOR_DELIVERY, date="2026-05-13", time="09:00", location="Sucursal Occidental", lat=8.5983, lng=-71.1476, operator="Conductor Pedro", completed=True),
            TrackingEvent(step=ParcelStatus.DELIVERED, date="2026-05-14", time="10:30", location="Av. Bolivar 456, Merida", lat=8.5983, lng=-71.1476, operator="Conductor Pedro", completed=True),
        ],
    }
